@echo off
echo Starting STEMQuest Backend...
start cmd /k "cd backend && .\venv\Scripts\activate.bat && python -m uvicorn app.main:app --reload"

echo Starting STEMQuest Frontend...
start cmd /k "cd frontend && npm run dev"

echo Both servers are starting...
